import { GetServerSideProps, InferGetServerSidePropsType } from "next";
import Head from "next/head";
import {} from "next/server";
import Board from "../components/board/Board";
import DarkModeButton from "../components/DarkModeButton";
import Keyboard from "../components/keyboard/Keyboard";
import useSettingsStore from "../state/settings";
import seedrandom from "seedrandom";
import answers from "../answers";

export const getServerSideProps: GetServerSideProps<{ word: string }> = async (
  context
) => {
  const rng = seedrandom(new Date().toDateString());
  const index = Math.floor(rng() * answers.length);
  const word = answers[index];
  return {
    props: {
      word,
    },
  };
};

export default function Home({
  word,
}: InferGetServerSidePropsType<typeof getServerSideProps>) {
  const { darkMode, toggleDarkMode } = useSettingsStore();
  return (
    <div
      className={`${
        darkMode ? "bg-black text-white" : "bg-white text-black"
      } w-screen h-screen transition-colors duration-500`}
    >
      <Head>
        <title>Next.js Wordle Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="w-full flex justify-center items-center border-b-gray-500 border-b-2">
        <div className="text-2xl font-bold">Wordle Clone</div>
        <div className="absolute right-0 pr-4 flex justify-center items-center">
          <DarkModeButton onClick={toggleDarkMode} darkMode={darkMode} />
        </div>
      </header>
      <main className="flex flex-col items-center">
        <div className="grow flex justify-center items-center">
          <Board />
        </div>
        {word}
        <Keyboard />
      </main>
    </div>
  );
}
